tutoringapp/response/urls.py
from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('',
    url(r'^$', 'response.views.all_responses'),
    url(r'^new/$', 'response.views.new_response'),
    url(r'^create/$', 'response.views.new_response'),
    url(r'^edit/(\d+)/$', 'response.views.edit_response'),
    url(r'^delete/(\d+)/$', 'response.views.delete_response'),
    url(r'^respond/$', 'response.views.respond'),
    )

tutoringapp/urls.py
from django.conf import settings
from django.conf.urls.defaults import *
from tmsutil import views

handler404 = 'tmsutil.views.handler404'
handler500 = 'tmsutil.views.handler500'

urlpatterns = patterns('',
        url(r'^$', 'account.views.home_page'),
        url(r'^manual/$', 'tmsutil.views.download_manual' ),
        url(r'^login/$', 'account.views.login_page' ),
        url(r'^account/', include('account.urls') ),
        url(r'^notification/', include('notification.urls') ),
        url(r'^tutors/', include('tutors.urls') ),
        url(r'^tutees/', include('tutees.urls') ),
        url(r'^matches/', include('match.urls') ),
        url(r'^respond/', include('response.urls') ),
        # Serve static assets for dev
        url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}),
    )

urlpatterns += patterns('',
    url(r'^captcha/', include('captcha.urls')),
)

tutoringapp/response/models.py
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db import models

class Response(models.Model):
    """ The base class for a response
    """
    name = models.CharField(max_length=255, unique=True, help_text="Name your response")
    description = models.CharField(max_length=255, help_text="Describe this response")
    response = models.TextField(blank=True,
            help_text="Response")
    created_by = models.ForeignKey(User)
    active = models.BooleanField(default=True)
    last_updated = models.DateTimeField(blank=False)

    def get_edit_url(self):
        return reverse('response.views.edit_response', args=[self.id])

    def get_delete_url(self):
        return reverse('response.views.delete_response', args=[self.id])

    def __unicode__(self):
        return self.name

tutoringapp/response/forms.py
from response.models import Response
from tmsutil.forms import TmsModelForm

class ResponseForm(TmsModelForm):
    class Meta:
        model = Response
        exclude = ('created_by', 'last_updated', 'active')

tutoringapp/response/views.py
from datetime import datetime
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render_to_response
from django.template import RequestContext
from notification.models import Notification
from response.forms import ResponseForm
from response.models import Response
from response.replacements import manual_replace, tutee_replace, tutor_replace
from tutees.models import Tutee
from tutors.models import Tutor

def all_responses(request):
    responses = Response.objects.filter(active=True)
    return render_to_response('response/all_responses.html', {
        'responses': responses,
        }, context_instance=RequestContext(request))

def new_response(request):
    if request.method == "POST":
        form = ResponseForm(request.POST)
        if form.is_valid():
            response = form.save(commit=False)
            response.last_updated = datetime.now()
            response.created_by = request.user
            response.active = 1
            response.save()
            Notification.objects.create_response(request.user, response)
            messages.success(request, "Added response")
            return HttpResponseRedirect(reverse('response.views.new_response',args=[]))
        else:
            messages.error(request, "Error adding response, please see errors below.")
    else:
        form = ResponseForm
    return render_to_response('response/new_response.html', {
        'form': form,
        }, context_instance=RequestContext(request))

def edit_response(request, response_id):
    response = get_object_or_404(Response, id=response_id)
    if request.method == "POST":
        form = ResponseForm(request.POST, instance=response)
        if form.is_valid():
            response = form.save(commit=False)
            response.last_updated = datetime.now()
            response.created_by = request.user
            response.save()
            Notification.objects.edit_response(request.user, response)
            messages.success(request, "Response saved.")
            return HttpResponseRedirect(reverse(
                'response.views.all_responses', args=[]))
        else:
            messages.error(request, "Error adding response, please see errors below.")
    else:
        form = ResponseForm(instance=response)
    return render_to_response('response/edit_response.html', {
            'form': form, 'response_id': response_id,
            }, context_instance=RequestContext(request))

def delete_response(request, response_id):
    response = get_object_or_404(Response, id=response_id)
    if request.method == "DELETE":
        response.active=False
        response.save()
        Notification.objects.delete_response(request.user, response)
    return HttpResponse("<h1>Success</h1>")

def respond(request):
    if request.is_ajax():
        response_id = request.GET.get('response')
        response = Response.objects.get(id=response_id).response
        tutor_id = request.GET.get('tutor')
        if tutor_id != "":
            tutor = Tutor.objects.get(id=tutor_id)
            response = tutor_replace(response, tutor)
        tutee_id = request.GET.get('tutee')
        if tutee_id != "":
            tutee = Tutee.objects.get(id=tutee_id)
            response = tutee_replace(response, tutee)
        response = manual_replace(response)
        return HttpResponse(response)
    responses = Response.objects.all()
    return render_to_response('response/respond.html', {
        'responses': responses
        }, context_instance=RequestContext(request))

tutoringapp/templates/response/all_responses.html
{% extends "base.html" %}
{% block body %}
<div class="crumbs">
  <a href="{% url response.views.respond %}">
    Respond
  </a>
  &#124;
  <a href="{% url response.views.all_responses %}" class="selected">
    All responses
  </a>
  &#124;
  <a href="{% url response.views.new_response %}">
    Create response
  </a>
</div>
{% for response in responses %}
<div class="response">
    <div class="w250 left bold">{{ response.name }}</div>
    <div class="w250 left italic">{{ response.description }}</div>
    <div class="clearfix"></div>
    <div>Last updated by {{ response.created_by.get_full_name }} at
        {{ response.last_updated }}.
        <a href="{{ response.get_edit_url }}">Edit</a>
        <a href="{{ response.get_delete_url }}" class="response-delete">Delete</a>
    </div>
    <div class="clearfix"></div><br/>
{{ response.response|safe }}
<br/>
<br/>
</div>
{% endfor %}
{% endblock body %}
{% block extrascript %}
<script type="text/javascript">
  $(document).ready(function() {
    $('#response-nav').addClass('selected');
  });
    responseDeleteHandlers();
</script>
{% endblock extrascript %}

tutoringapp/templates/response/edit_response.html
{% extends "base.html" %}
{% block body %}
<div class="crumbs">
  <a href="{% url response.views.respond %}">
    Respond
  </a>
  &#124;
  <a href="{% url response.views.all_responses %}">
    All responses
  </a>
  &#124;
  <a href="{% url response.views.new_response %}">
    Create response
  </a>
</div>
<h2>Edit Response</h2>
<form class="tut-form" action="{% url response.views.edit_response response_id %}" method="post">
    {% include "snippets/response_form.html" %}
    <br/>
    <input type="submit" class="form-but" value="Save" />
    <a href="{% url response.views.all_responses %}">
        <input type="reset" class="form-but" value="Cancel" />
    </a>
</form>
{% endblock body %}
{% block extrascript %}
<script type="text/javascript"
    src="{{MEDIA_URL}}plugins/cleditor/jquery.cleditor.min.js">
</script>
<script type="text/javascript">
  $(function() {
    $('#id_response').cleditor();
    $('#response-nav').addClass('selected');
  });
</script>
{% endblock extrascript %}
{% block extrastyle %}
    <link rel="stylesheet" type="text/css"
        href="{{MEDIA_URL}}plugins/cleditor/jquery.cleditor.css" />
{% endblock extrastyle %}

tutoringapp/templates/response/new_response.html
{% extends "base.html" %}
{% block body %}
<div class="crumbs">
  <a href="{% url response.views.respond %}">
    Respond
  </a>
  &#124;
  <a href="{% url response.views.all_responses %}">
    All responses
  </a>
  &#124;
  <a href="{% url response.views.new_response %}" class="selected">
    Create response
  </a>
</div>
<h2>New Response</h2>
<form class="tut-form" action="{% url response.views.new_response %}" method="post">
    {% include "snippets/response_form.html" %}
    <br/>
    <input type="submit" class="form-but" value="Save" />
</form>
{% endblock body %}
{% block extrascript %}
<script type="text/javascript"
    src="{{MEDIA_URL}}plugins/cleditor/jquery.cleditor.min.js">
</script>
<script type="text/javascript">
  $(function() {
    $('#id_response').cleditor();
    $('#response-nav').addClass('selected');
  });
</script>
{% endblock extrascript %}
{% block extrastyle %}
    <link rel="stylesheet" type="text/css"
        href="{{MEDIA_URL}}plugins/cleditor/jquery.cleditor.css" />
{% endblock extrastyle %}

tutoringapp/templates/response/respond.html
{% extends "base.html" %}
{% block body %}
<div class="crumbs">
  <a href="{% url response.views.respond %}" class="selected">
    Respond
  </a>
  &#124;
  <a href="{% url response.views.all_responses %}">
    All responses
  </a>
  &#124;
  <a href="{% url response.views.new_response %}">
    Create response
  </a>
</div>
<h1>Respond</h1>
<form action="{% url response.views.respond %}" id="get-response" method="get">
<input id="tutee-resp" placeholder="Tutee Name" class="resp-autocomplete"
    rel="{% url tutees.views.search_ajax %}"/>
<input id="tutee-resp-val" name="tutee" type="hidden"/>

<input id="tutor-resp" placeholder="Tutor Name" class="resp-autocomplete"
    rel="{% url tutors.views.search_ajax %}"/>
<input id="tutor-resp-val" name="tutor" type="hidden"/>
<select name="response">
    {% for response in responses %}
    <option value="{{response.id}}">
        {{response.name}}
    </option>
    {% endfor %}
</select>
<button>Get response</button>
<br/>
<div class="response-div-header">Response</div>
<div class="clearfix"></div>
<div id="response-div" class="ui-corner-all"></div>
{% endblock body %}
{% block extrascript %}
<script type="text/javascript">
  $(function() {
    responseAutocompleteInit();
    $('#response-nav').addClass('selected');
    getResponseInit();
  });
</script>
{% endblock extrascript %}